apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        resources:
          limits:
             memory: "128Mi"
             cpu: "500m"
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                key: mongo-root-username
                name: mongodb-secret   
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                key: mongo-root-password
                name: mongodb-secret      
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                key: database-url
                name: mongodb-configmap
---
kind: Service
apiVersion: v1
metadata:
  name:  mongodb-external-service
spec:
  selector:
    app:  mongo-express
  type: LoadBalancer
  ports:
  - protocol:  TCP
    port:  8081
    targetPort:  8081
    nodePort: 30000
                     